name: Action Repository Dispatch
author: 'Tony DBR'
description: Send customized repository_dispatch events
branding:
  color: green
  icon: send

inputs:
  targetRepository:
    description: Full name (owner/repo-name) of the repository that will receive the repository_dispatch event
    required: false
    default: ${{ github.repository }}

  eventType:
    description: Custom event type expected by the receiving repository
    required: true

  token:
    description: A GitHub Personal Access Token (PAT) with 'repo' permissions
    required: true

  payloadType:
    description: "Type of payload provided. Types: string, path, url"
    required: false
    default: 'string'

  payload:
    description: Stringified JSON payload. Expected when payloadType is not provided or provided as "string"
    required: false
    default: '{}'

  payloadPath:
    description: Path to file with JSON payload. Expected when payloadType is provided as "path"
    required: false

  payloadUrl:
    description: URL to JSON payload. Expected when payloadType is provided as "url"
    required: false


runs:
  using: 'node16'
  main: 'dist/index.js'
